availableCities = [
{cityName: "Athens+ga",  wikiName:"Athens,_Georgia" },
{cityName: "Atlanta", wikiName:"Atlanta" },
{cityName: "Austin", wikiName:"Austin,_Texas" },
{cityName: "Berlin",  wikiName:"Berlin" },
{cityName: "Berkeley",  wikiName:"Berkeley,_California" },
{cityName: "Birmingham", wikiName:"Birmingham" },
{cityName: "Borlange", wikiName:"Borlänge" },
{cityName: "Boston", wikiName:"Boston" },
{cityName: "Bristol", wikiName:"Bristol" },
{cityName: "Charlotte", wikiName:"Charlotte,_North_Carolina" },
{cityName: "Chicago", wikiName:"Chicago" },
{cityName: "Detroit", wikiName:"Detroit" },
{cityName: "Glasgow", wikiName:"Glasgow" },
{cityName: "Gothenburg", wikiName:"Gothenburg" },
{cityName: "Havana", wikiName:"Havana" },
{cityName: "London", wikiName:"London" },
{cityName: "Los Angeles", wikiName:"Los_Angeles" },
{cityName: "Manchester", wikiName:"Manchester" },
{cityName: "Memphis", wikiName:"Memphis" },
{cityName: "Moscow", wikiName:"Moscow" },
{cityName: "Nashville", wikiName:"Nashville" },
{cityName: "New Orleans", wikiName:"New_Orleans" },
{cityName: "New York", wikiName:"New_York" },
{cityName: "Oslo", wikiName:"Oslo" },
{cityName: "Palm Desert", wikiName:"Palm_Desert" },
{cityName: "Paris", wikiName:"Paris" },
{cityName: "Reykjavik", wikiName:"Reykjavík" },
{cityName: "Rome", wikiName:"Rome" },
{cityName: "San Francisco", wikiName:"San_Francisco"},
{cityName: "Seattle", wikiName:"Seattle" },
{cityName: "Sheffield", wikiName:"Sheffield" },
{cityName: "Stockholm", wikiName:"Stockholm" },
{cityName: "Sydney", wikiName:"Sydney" },
{cityName: "Tokyo", wikiName:"Tokyo" }
];

//availableCities = [ {cityName: "Borlange", wikiName:"Borlänge" },];